---
abstract: 'interface to Pushover API'
author:
  - 'Steve Huff <shuff@cpan.org>'
build_requires:
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Pushover
provides:
  WebService::Pushover:
    file: lib/WebService/Pushover.pm
    version: v0.1.1
requires:
  DateTime: 0
  DateTime::Format::Strptime: 0
  File::Spec: 0
  Moo: 0
  Net::HTTP::Spore: 0
  Net::HTTP::Spore::Middleware::Header: 0
  Params::Validate: 0
  Readonly: 0
  URI: 0
  perl: 5.008
  version: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=WebService-Pushover
  homepage: https://github.com/hakamadare/webservice-pushover
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hakamadare/webservice-pushover.git
version: v0.1.1
